FROM tattaka/ml_environment:base

MAINTAINER tattaka


RUN pip install --upgrade pip==9.0.3 && pip install \
  future \
  torch==1.4.0 \
  torchvision==0.5.0 \
  tensorboard 

WORKDIR /root/ml_environment

ENTRYPOINT []
CMD [ "/bin/bash" ]
