FROM tattaka/ml_environment:base

MAINTAINER tattaka


RUN pip install --upgrade pip==9.0.3 && pip install \
  future \
  torch \
  torchvision \
  tensorboard 

WORKDIR /root/ml_environment

ENTRYPOINT []
CMD [ "/bin/bash" ]
